export const common = {
  blockstackIcon: require('./blockstackIcon.png'),
  logo: require('./eye-logo.png'),
  searchIcon: require('./search.png'),
  gif: require('./gif.png'),
  mic: require('./mic.png'),
  photo: require('./photo.png'),
  stats: require('./stats.png'),
  chevron: require('./chevron.png'),
  publicImage: require('./public.png'),
  avatar: require('./data-avatar.png'),
  lock: require('./lock.png'),
  notification: require('./notifications.png'),
  notificationActive: require('./notifications-active.png'),
};
